<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <BaseOutputPath>bin</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);UNITY_EDITOR;UNITY_2021_OR_NEWER;UNITY_2021_OR_NEWER;UNITY_EDITOR</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp-Editor">
      <HintPath>bin\Debug\netstandard2.0\Assembly-CSharp-Editor.dll</HintPath>
    </Reference>
    <Reference Include="LoopScrollRect.Runtime">
      <HintPath>bin\Debug\netstandard2.0\LoopScrollRect.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>bin\Debug\netstandard2.1\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="RTLTMPro">
      <HintPath>bin\Debug\netstandard2.0\RTLTMPro.dll</HintPath>
    </Reference>
    <Reference Include="spine-csharp">
      <HintPath>bin\Debug\netstandard2.0\spine-csharp.dll</HintPath>
    </Reference>
    <Reference Include="spine-unity">
      <HintPath>bin\Debug\netstandard2.0\spine-unity.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>bin\Debug\netstandard2.0\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor">
      <HintPath>bin\Debug\netstandard2.0\UnityEditor.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor.CoreModule">
      <HintPath>bin\Debug\netstandard2.0\UnityEditor.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>bin\Debug\netstandard2.0\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>bin\Debug\netstandard2.0\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>bin\Debug\netstandard2.0\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>bin\Debug\netstandard2.0\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>bin\Debug\netstandard2.0\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>bin\Debug\netstandard2.0\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetName).dll&quot; &quot;D:\pro_yangjie\Assets\Plugins\Editor\&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).pdb&quot; &quot;D:\pro_yangjie\Assets\Plugins\Editor\&quot; /Y " />
  </Target>
  


</Project>
